# Generated by Django 2.1.5 on 2019-01-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
            ],
        ),
    ]
