# Generated by Django 2.1.5 on 2019-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20190203_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('fileinput', models.ImageField(upload_to='faces/')),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
